### ISSUE TITLE
Add database for querying

### ISSUE THREAD

**Issue by matteocasotto** [matteocasotto/guitarists#1]
- Write script to populate and delete database
- Write a manager class to handle all calls to database

**Comment by 871523** [comment]
Added manager in c642467453250510966eb3a8b685f17b0f52a321

**Comment by matteocasotto** [comment]
Added script in 13f71b04414264106c7c391fb7143e75d8d8804b

**Comment by AlbertoMarchesini** [comment]
Reopen. Use Wikipedia API to get a larger list of guitarists from https://en.wikipedia.org/wiki/List_of_guitarists

**Comment by AlbertoMarchesini** [comment]
Added in 5ee8dbfa99c617d9f730b3410f951509a1eaeef0
