### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by matteocasotto** [matteocasotto/guitarists#5]
- Add tests for database
- Add tests for cache

**Comment by matteocasotto** [comment]
Database's tests added in 7a06120076fd3f82fa216c9c1780bf8ee321cc9b

**Comment by AlbertoMarchesini** [comment]
Added cache's tests in de12bc588856aa7d246b86c42984df40f7c2c0fa

**Comment by matteocasotto** [comment]
Added cache's tests in de12bc588856aa7d246b86c42984df40f7c2c0fa
